apiVersion: v1
kind: ServiceAccount
metadata:
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  namespace: openshift-sro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  namespace: openshift-sro
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
#  - hostmount-anyuid 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  namespace: openshift-sro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  namespace: openshift-sro
subjects:
- kind: ServiceAccount
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  namespace: openshift-sro
userNames:
- system:serviceaccount:openshift-sro:specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
  annotations:
    specialresource.openshift.io/wait: "true"
  labels:
    app.kubernetes.io/name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
    app.kubernetes.io/version: 1.0.0-alpha
    app.kubernetes.io/part-of: nvidia-gpu
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
      app.kubernetes.io/part-of: nvidia-gpu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
        app.kubernetes.io/version: 1.0.0-alpha
        app.kubernetes.io/part-of: nvidia-gpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: specialresource.openshift.io/device-plugin-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
                operator: In 
                values:
                - ready 
      tolerations:
        - operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
      effect: NoSchedule
      serviceAccount: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
      serviceAccountName: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
      containers:
        - image: quay.io/openshift-psap/nvidia-feature-discovery  # nvidia/gpu-feature-discovery:1.0.0-alpha
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: NVIDIA_REQUIRE_CUDA  
              value: "cuda>=5.0"
          name: specialresource-feature-discovery-SPECIALRESOURCE.OPENSHIFT.IO.HARDWARE
          securityContext:
            privileged: true
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-product-name
              mountPath: "/sys/class/dmi/id/product_name"
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        SPECIALRESOURCE.OPENSHIFT.IO.NODEFEATURE: "true" 